"""empty message

Revision ID: 42492c1c6fdc
Revises: a84c960df1e0
Create Date: 2024-11-19 00:41:48.418973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42492c1c6fdc'
down_revision = 'a84c960df1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
