"""empty message

Revision ID: 4e640f45e50d
Revises: 56ebbb4bd0ee
Create Date: 2024-12-18 00:07:45.678487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e640f45e50d'
down_revision = '56ebbb4bd0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_anime', schema=None) as batch_op:
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
