"""empty message

Revision ID: 56ebbb4bd0ee
Revises: 8b360ef7b609
Create Date: 2024-12-14 00:41:38.433124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ebbb4bd0ee'
down_revision = '8b360ef7b609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_anime', schema=None) as batch_op:
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###
