"""empty message

Revision ID: ca15af4916a4
Revises: 7af0cb66fdcf
Create Date: 2024-12-19 00:32:36.027036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca15af4916a4'
down_revision = '7af0cb66fdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_anime', schema=None) as batch_op:
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
